### ISSUE TITLE
Practica 1 Mockup 

### ISSUE THREAD

**Issue by HECTOR-KDM02** [SistemasTecTlaxiaco/actividad-1-practicaprototipo-team-ola#2]
[Practica-1--Topicos-avanzados-de-programacion.pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-practicaprototipo-team-ola/files/14285306/Practica-1--Topicos-avanzados-de-programacion.pdf) (REPORTE)
https://www.figma.com/file/6E5DQVFdOJ9iNuyXt4TwHl/Untitled?type=design&node-id=0-1&mode=design&t=T0cRo5RgFVZ5yhWv-0 (Mockup)

**Comment by Bryan080204** [comment]
Como equipo designado a calificar este trabajo basándonos en las rubricas del docente
concluimos que cumple con la mayoria de los criterios a desarrollar en su proyecto, cumple con un buen procedimiento , sus figuras e ilustraciones son correctos ,los resultados y conclucion estan bien redactadas base a su interfaz.
Los detalles solo fueron unos datos en la protada.

calificaion: 19.4

**Comment by josealfredo79** [comment]
Calificacion 19.4 Bien hecho y realizado...felicidades...
